import { createContext, useState, useEffect, useContext } from "react";

export const LanguageContext = createContext();

export const translations = {
  en: {
    // Nav & General
    home: "Home",
    products: "Products",
    categories: "Categories",
    cart: "Cart",
    wishlist: "Wishlist",
    orders: "My Orders",
    profile: "Profile & Settings",
    login: "Login",
    logout: "Logout",
    search_placeholder: "Search for products, brands and more (e.g. MacBook, Sony, iPhone)...",
    search_btn: "Search",
    theme_light: "Light Mode",
    theme_dark: "Dark Mode",
    language: "Language",
    compare: "Compare",
    voice_ai: "Aura AI",
    delivery_to: "Deliver to",
    
    // Home & Catalog
    hero_title: "India's Smart Next-Gen E-Commerce Marketplace",
    hero_sub: "Experience ultrafast delivery, authentic products, Aura AI voice navigation, and multi-portal operations.",
    shop_now: "Shop Now",
    explore_deals: "Explore Deals",
    featured_categories: "Featured Categories",
    trending_products: "Trending Products",
    add_to_cart: "Add to Cart",
    buy_now: "Buy Now",
    in_stock: "In Stock",
    out_of_stock: "Out of Stock",
    free_delivery: "Free Delivery",
    fast_delivery: "24-Hour Express Delivery",
    rating: "Rating",
    reviews: "Reviews",
    discount: "OFF",
    
    // Profile & Settings
    personal_info: "Personal Information",
    current_orders: "Current Active Orders",
    past_orders: "Past Order History",
    no_active_orders: "No active orders in transit.",
    no_past_orders: "No past orders found.",
    track_order: "Track Live Order",
    invoice_download: "View Invoice",
    reorder: "Reorder Item",
    account_settings: "Account & Preferences",
    theme_setting: "Display Theme",
    language_setting: "Preferred Language",
    save_settings: "Save Preferences",
    phone_number: "Phone Number",
    postal_code: "PIN / Postal Code",
    shipping_address: "Shipping Address",
    email_address: "Email Address",
    full_name: "Full Name",
    city: "City",
    state: "State",
    
    // Checkout
    checkout_title: "Secure Checkout",
    contact_details: "Contact & Delivery Information",
    enter_phone: "Enter 10-digit Phone Number",
    enter_address: "Flat, House no., Building, Street, Area",
    enter_pincode: "6-digit Postal PIN Code",
    enter_email: "Enter Email for Order Updates",
    payment_method: "Payment Method",
    cod: "Cash on Delivery",
    online_pay: "Online Payment / UPI / Cards",
    place_order: "Place Your Order",
    order_summary: "Order Summary",
    total_payable: "Total Payable",
    
    // Aura Voice AI
    aura_greeting: "Vanakkam! I am Aura AI, your smart shopping & voice navigation assistant.",
    aura_listening: "Aura AI is listening... Speak your command in your language",
    aura_placeholder: "Ask Aura AI to navigate or compare (English, தமிழ், हिन्दी, മലയാളം, ಕನ್ನಡ, ଓଡ଼ିଆ)...",
    aura_voice_shortcuts: "Voice Shortcuts",
    ask_aura: "Ask Aura"
  },
  
  ta: {
    // Tamil
    home: "முகப்பு",
    products: "பொருட்கள்",
    categories: "பிரிவுகள்",
    cart: "கூடை",
    wishlist: "விருப்பப்பட்டியல்",
    orders: "எனது ஆர்டர்கள்",
    profile: "சுயவிவரம் & அமைப்புகள்",
    login: "உள்நுழைக",
    logout: "வெளியேறு",
    search_placeholder: "பொருட்கள், பிராண்டுகளை தேடுங்கள்...",
    search_btn: "தேடு",
    theme_light: "பகற்பொழுது முறை",
    theme_dark: "இரவு முறை",
    language: "மொழி",
    compare: "ஒப்பீடு",
    voice_ai: "Aura AI",
    delivery_to: "டெலிவரி முகவரி",
    hero_title: "இந்தியாவின் அதிநவீன மின்-வணிக தளம்",
    hero_sub: "விரைவான டெலிவரி, அசல் தயாரிப்புகள் மற்றும் Aura AI குரல் வழிகாட்டுதல்.",
    shop_now: "இப்போது வாங்கவும்",
    explore_deals: "சலுகைகளை காண்க",
    featured_categories: "முக்கிய பிரிவுகள்",
    trending_products: "பிரபலமான பொருட்கள்",
    add_to_cart: "கூடையில் சேர்",
    buy_now: "இப்போதே வாங்கு",
    in_stock: "கையிருப்பில் உள்ளது",
    out_of_stock: "கையிருப்பில் இல்லை",
    free_delivery: "இலவச டெலிவரி",
    fast_delivery: "24 மணிநேர விரைவு டெலிவரி",
    rating: "மதிப்பீடு",
    reviews: "மதிப்புரைகள்",
    discount: "தள்ளுபடி",
    personal_info: "தனிப்பட்ட விவரங்கள்",
    current_orders: "தற்போதைய ஆர்டர்கள்",
    past_orders: "முந்தைய ஆர்டர்கள்",
    no_active_orders: "செயலில் உள்ள ஆர்டர்கள் இல்லை.",
    no_past_orders: "முந்தைய ஆர்டர்கள் இல்லை.",
    track_order: "ஆர்டரைக் கண்காணிக்கவும்",
    invoice_download: "விலைப் பட்டியல்",
    reorder: "மீண்டும் ஆர்டர் செய்க",
    account_settings: "கணக்கு & விருப்பத்தேர்வுகள்",
    theme_setting: "வண்ண தீம்",
    language_setting: "விருப்ப மொழி",
    save_settings: "சேமிக்கவும்",
    phone_number: "தொலைபேசி எண்",
    postal_code: "அஞ்சல் குறியீடு (PIN)",
    shipping_address: "டெலிவரி முகவரி",
    email_address: "மின்னஞ்சல் முகவரி",
    full_name: "முழு பெயர்",
    city: "நகரம்",
    state: "மாநிலம்",
    checkout_title: "பாதுகாப்பான செக்அவுட்",
    contact_details: "தொடர்பு & டெலிவரி விவரங்கள்",
    enter_phone: "10-இலக்க தொலைபேசி எண்",
    enter_address: "வீட்டு எண், தெரு மற்றும் பகுதி",
    enter_pincode: "6-இலக்க அஞ்சல் குறியீடு",
    enter_email: "மின்னஞ்சல் முகவரி உள்ளிடவும்",
    payment_method: "பணம் செலுத்தும் முறை",
    cod: "டெலிவரியின் போது பணம்",
    online_pay: "ஆன்லைன் / UPI / கார்டுகள்",
    place_order: "ஆர்டர் உறுதி செய்க",
    order_summary: "ஆர்டர் சுருக்கம்",
    total_payable: "மொத்த தொகை",
    aura_greeting: "வணக்கம்! நான் Aura AI, உங்கள் குரல் வழிகாட்டி & ஷாப்பிங் உதவியாளர்.",
    aura_listening: "Aura AI கேட்கிறது... உங்கள் குரலில் பேசுங்கள்",
    aura_placeholder: "Aura AI-யிடம் கேட்கவும் அல்லது கட்டளையிடவும்...",
    aura_voice_shortcuts: "குரல் குறுக்குவழிகள்",
    ask_aura: "Ask Aura"
  },

  hi: {
    // Hindi
    home: "होम",
    products: "उत्पाद",
    categories: "श्रेणियां",
    cart: "कार्ट",
    wishlist: "विशलिस्ट",
    orders: "मेरे ऑर्डर्स",
    profile: "प्रोफ़ाइल और सेटिंग्स",
    login: "लॉग इन",
    logout: "लॉग आउट",
    search_placeholder: "उत्पाद, ब्रांड और अन्य खोजें...",
    search_btn: "खोजें",
    theme_light: "लाइट मोड",
    theme_dark: "डार्क मोड",
    language: "भाषा",
    compare: "तुलना करें",
    voice_ai: "Aura AI",
    delivery_to: "डिलीवरी पता",
    hero_title: "भारत का स्मार्ट नेक्स्ट-जेन ई-कॉमर्स मार्केटप्लेस",
    hero_sub: "सुपरफास्ट डिलीवरी, प्रामाणिक उत्पाद और Aura AI वॉयस नेविगेशन।",
    shop_now: "अभी खरीदें",
    explore_deals: "ऑफ़र देखें",
    featured_categories: "प्रमुख श्रेणियां",
    trending_products: "लोकप्रिय उत्पाद",
    add_to_cart: "कार्ट में जोड़ें",
    buy_now: "तुरंत खरीदें",
    in_stock: "उपलब्ध है",
    out_of_stock: "स्टॉक में नहीं है",
    free_delivery: "मुफ़्त डिलीवरी",
    fast_delivery: "24 घंटे एक्सप्रेस डिलीवरी",
    rating: "रेटिंग",
    reviews: "समीक्षाएं",
    discount: "छूट",
    personal_info: "व्यक्तिगत जानकारी",
    current_orders: "वर्तमान सक्रिय ऑर्डर्स",
    past_orders: "पुराने ऑर्डर्स का इतिहास",
    no_active_orders: "कोई सक्रिय ऑर्डर नहीं है।",
    no_past_orders: "कोई पिछला ऑर्डर नहीं मिला।",
    track_order: "लाइव ऑर्डर ट्रैक करें",
    invoice_download: "इनवॉइस देखें",
    reorder: "पुनः ऑर्डर करें",
    account_settings: "खाता और प्राथमिकताएं",
    theme_setting: "डिस्प्ले थीम",
    language_setting: "पसंदीदा भाषा",
    save_settings: "सेव करें",
    phone_number: "फ़ोन नंबर",
    postal_code: "पिन कोड",
    shipping_address: "डिलीवरी का पता",
    email_address: "ईमेल पता",
    full_name: "पूरा नाम",
    city: "शहर",
    state: "राज्य",
    checkout_title: "सुरक्षित चेकआउट",
    contact_details: "संपर्क और डिलीवरी विवरण",
    enter_phone: "10 अंकों का फ़ोन नंबर दर्ज करें",
    enter_address: "मकान नं, गली और क्षेत्र",
    enter_pincode: "6 अंकों का पिन कोड",
    enter_email: "ईमेल दर्ज करें",
    payment_method: "भुगतान का प्रकार",
    cod: "कैश ऑन डिलीवरी",
    online_pay: "ऑनलाइन भुगतान / UPI / कार्ड",
    place_order: "ऑर्डर दें",
    order_summary: "ऑर्डर सारांश",
    total_payable: "कुल देय राशि",
    aura_greeting: "नमस्ते! मैं Aura AI हूँ, आपका स्मार्ट वॉयस और शॉपिंग सहायक।",
    aura_listening: "Aura AI सुन रहा है... अपना आदेश अपनी भाषा में बोलें",
    aura_placeholder: "Aura AI से पूछें या नेविगेट करें...",
    aura_voice_shortcuts: "वॉयस शॉर्टकट",
    ask_aura: "Ask Aura"
  },

  ml: {
    // Malayalam
    home: "ഹോം",
    products: "ഉൽപന്നങ്ങൾ",
    categories: "വിഭാഗങ്ങൾ",
    cart: "കാർട്ട്",
    wishlist: "വിഷ്‌ലിസ്റ്റ്",
    orders: "എന്റെ ഓർഡറുകൾ",
    profile: "പ്രൊഫൈൽ & ക്രമീകരണങ്ങൾ",
    login: "ലോഗിൻ",
    logout: "ലോഗ് ഔട്ട്",
    search_placeholder: "ഉൽപന്നങ്ങളും ബ്രാൻഡുകളും തിരയുക...",
    search_btn: "തിരയുക",
    theme_light: "ലൈറ്റ് മോഡ്",
    theme_dark: "ഡാർക്ക് മോഡ്",
    language: "ഭാഷ",
    compare: "താരതമ്യം ചെയ്യുക",
    voice_ai: "Aura AI",
    delivery_to: "ഡെലിവറി വിലാസം",
    hero_title: "ഇന്ത്യയുടെ മികച്ച സ്മാർട്ട് ഇ-കൊമേഴ്സ് പ്ലാറ്റ്ഫോം",
    hero_sub: "വേഗത്തിലുള്ള ഡെലിവറിയും ഒറിജിനൽ ഉൽപന്നങ്ങളും Aura AI വോയ്സ് വഴികാട്ടലും.",
    shop_now: "ഇപ്പോൾ വാങ്ങുക",
    explore_deals: "ഓഫറുകൾ കാണുക",
    featured_categories: "പ്രധാന വിഭാഗങ്ങൾ",
    trending_products: "ജനപ്രിയ ഉൽപന്നങ്ങൾ",
    add_to_cart: "കാർട്ടിൽ ചേർക്കുക",
    buy_now: "ഇപ്പോൾ വാങ്ങുക",
    in_stock: "സ്റ്റോക്കിൽ ഉണ്ട്",
    out_of_stock: "സ്റ്റോക്കിൽ ഇല്ല",
    free_delivery: "സൗജന്യ ഡെലിവറി",
    fast_delivery: "24 മണിക്കൂർ അതിവേഗ ഡെലിവറി",
    rating: "റേറ്റിംഗ്",
    reviews: "റിവ്യൂകൾ",
    discount: "കിഴിവ്",
    personal_info: "വ്യക്തിഗത വിവരങ്ങൾ",
    current_orders: "നിലവിലെ ഓർഡറുകൾ",
    past_orders: "കഴിഞ്ഞ ഓർഡറുകൾ",
    no_active_orders: "നിലവിൽ ആക്റ്റീവ് ഓർഡറുകൾ ഇല്ല.",
    no_past_orders: "മുൻകാല ഓർഡറുകൾ ഒന്നും ലഭ്യമല്ല.",
    track_order: "ഓർഡർ ട്രാക്ക് ചെയ്യുക",
    invoice_download: "ഇൻവോയ്സ് കാണുക",
    reorder: "വീണ്ടും ഓർഡർ ചെയ്യുക",
    account_settings: "അക്കൗണ്ട് & ക്രമീകരണങ്ങൾ",
    theme_setting: "തീം",
    language_setting: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    save_settings: "സേവ് ചെയ്യുക",
    phone_number: "ഫോൺ നമ്പർ",
    postal_code: "പിൻ കോഡ്",
    shipping_address: "ഡെലിവറി വിലാസം",
    email_address: "ഇമെയിൽ വിലാസം",
    full_name: "പൂർണ്ണ നാമം",
    city: "നഗരം",
    state: "സംസ്ഥാനം",
    checkout_title: "സുരക്ഷിത ചെക്ക്ഔട്ട്",
    contact_details: "ഡെലിവറി വിവരങ്ങൾ",
    enter_phone: "10 അക്ക ഫോൺ നമ്പർ നൽകുക",
    enter_address: "വീട്ടുപേര്, തെരുവ്, പ്രദേശം",
    enter_pincode: "6 അക്ക പിൻ കോഡ് നൽകുക",
    enter_email: "ഇമെയിൽ നൽകുക",
    payment_method: "പേയ്മെന്റ് രീതി",
    cod: "ക്യാഷ് ഓൺ ഡെലിവറി",
    online_pay: "ഓൺലൈൻ / UPI / കാർഡുകൾ",
    place_order: "ഓർഡർ നൽകുക",
    order_summary: "ഓർഡർ വിവരങ്ങൾ",
    total_payable: "ആകെ തുക",
    aura_greeting: "നമസ്കാരം! ഞാൻ Aura AI, നിങ്ങളുടെ സ്മാർട്ട് വോയ്സ് & ഷോപ്പിംഗ് അസിസ്റ്റന്റ്.",
    aura_listening: "Aura AI കേൾക്കുന്നു... സ്വന്തം ഭാഷയിൽ സംസാരിക്കൂ",
    aura_placeholder: "Aura AI-യോട് ചോദിക്കുക...",
    aura_voice_shortcuts: "വോയ്സ് കുറുക്കുവഴികൾ",
    ask_aura: "Ask Aura"
  },

  kn: {
    // Kannada
    home: "ಮುಖಪುಟ",
    products: "ಉತ್ಪನ್ನಗಳು",
    categories: "ವರ್ಗಗಳು",
    cart: "ಕಾರ್ಟ್",
    wishlist: "ವಿಶ್‌ಲಿಸ್ಟ್",
    orders: "ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    profile: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗ್ ಔಟ್",
    search_placeholder: "ಉತ್ಪನ್ನಗಳು, ಬ್ರ್ಯಾಂಡ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
    search_btn: "ಹುಡುಕಿ",
    theme_light: "ಲೈಟ್ ಮೋಡ್",
    theme_dark: "ಡಾರ್ಕ್ ಮೋಡ್",
    language: "ಭಾಷೆ",
    compare: "ಹೋಲಿಸಿ",
    voice_ai: "Aura AI",
    delivery_to: "ವಿತರಣಾ ವಿಳಾಸ",
    hero_title: "ಭಾರತದ ಅತ್ಯಾಧುನಿಕ ಇ-ಕಾಮರ್ಸ್ ಮಾರುಕಟ್ಟೆ",
    hero_sub: "ವೇಗದ ವಿತರಣೆ, ನೈಜ ಉತ್ಪನ್ನಗಳು ಮತ್ತು Aura AI ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ.",
    shop_now: "ಈಗ ಖರೀದಿಸಿ",
    explore_deals: "ಆಫರ್‌ಗಳನ್ನು ನೋಡಿ",
    featured_categories: "ಮುಖ್ಯ ವರ್ಗಗಳು",
    trending_products: "ಜನಪ್ರಿಯ ಉತ್ಪನ್ನಗಳು",
    add_to_cart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    buy_now: "ತಕ್ಷಣ ಖರೀದಿಸಿ",
    in_stock: "ಲಭ್ಯವಿದೆ",
    out_of_stock: "ಖಾಲಿಯಾಗಿದೆ",
    free_delivery: "ಉಚಿತ ಡೆಲಿವರಿ",
    fast_delivery: "24 ಗಂಟೆಗಳಲ್ಲಿ ಎಕ್ಸ್‌ಪ್ರೆಸ್ ಡೆಲಿವರಿ",
    rating: "ರೇಟಿಂಗ್",
    reviews: "ವಿಮರ್ಶೆಗಳು",
    discount: "ರಿಯಾಯಿತಿ",
    personal_info: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    current_orders: "ಪ್ರಸ್ತುತ ಆರ್ಡರ್‌ಗಳು",
    past_orders: "ಹಿಂದಿನ ಆರ್ಡರ್‌ಗಳು",
    no_active_orders: "ಯಾವುದೇ ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ.",
    no_past_orders: "ಹಿಂದಿನ ಆರ್ಡರ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    track_order: "ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    invoice_download: "ಇನ್‌ವಾಯ್ಸ್ ವೀಕ್ಷಿಸಿ",
    reorder: "ಮರು-ಆರ್ಡರ್ ಮಾಡಿ",
    account_settings: "ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳು",
    theme_setting: "ಡಿಸ್ಪ್ಲೇ ಥೀಮ್",
    language_setting: "ಆದ್ಯತೆಯ ಭಾಷೆ",
    save_settings: "ಉಳಿಸಿ",
    phone_number: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
    postal_code: "ಪಿನ್ ಕೋಡ್",
    shipping_address: "ಡೆಲಿವರಿ ವಿಳಾಸ",
    email_address: "ಇಮೇಲ್ ವಿಳಾಸ",
    full_name: "ಪೂರ್ಣ ಹೆಸರು",
    city: "ನಗರ",
    state: "ರಾಜ್ಯ",
    checkout_title: "ಸುರಕ್ಷಿತ ಚೆಕ್‌ಔಟ್",
    contact_details: "ಸಂಪರ್ಕ ಮತ್ತು ಡೆಲಿವರಿ ವಿವರಗಳು",
    enter_phone: "10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    enter_address: "ಮನೆ ನಂ, ರಸ್ತೆ ಮತ್ತು ಪ್ರದೇಶ",
    enter_pincode: "6 ಅಂಕಿಗಳ ಪಿನ್ ಕೋಡ್",
    enter_email: "ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ",
    payment_method: "ಪಾವತಿ ವಿಧಾನ",
    cod: "ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ",
    online_pay: "ಆನ್‌ಲೈನ್ ಪಾವತಿ / UPI / ಕಾರ್ಡ್‌ಗಳು",
    place_order: "ಆರ್ಡರ್ ಮಾಡಿ",
    order_summary: "ಆರ್ಡರ್ ವಿವರ",
    total_payable: "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
    aura_greeting: "ನಮಸ್ಕಾರ! ನಾನು Aura AI, ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಧ್ವನಿ ಮತ್ತು ಶಾಪಿಂಗ್ ಸಹಾಯಕ.",
    aura_listening: "Aura AI ಆಲಿಸುತ್ತಿದೆ... ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
    aura_placeholder: "Aura AI ಯನ್ನು ಕೇಳಿ...",
    aura_voice_shortcuts: "ಧ್ವನಿ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು",
    ask_aura: "Ask Aura"
  },

  or: {
    // Odia
    home: "ମୂଳପୃଷ୍ଠା",
    products: "ଉତ୍ପାଦଗୁଡ଼ିକ",
    categories: "ବିଭାଗ",
    cart: "କାର୍ଟ",
    wishlist: "ଇଚ୍ଛାତାଲିକା",
    orders: "ମୋର ଅର୍ଡର",
    profile: "ପ୍ରୋଫାଇଲ୍ ଏବଂ ସେଟିଙ୍ଗ୍ସ",
    login: "ଲଗଇନ୍",
    logout: "ଲଗଆଉଟ୍",
    search_placeholder: "ଉତ୍ପାଦ ଏବଂ ବ୍ରାଣ୍ଡ୍ ଖୋଜନ୍ତୁ...",
    search_btn: "ଖୋଜନ୍ତୁ",
    theme_light: "ଲାଇଟ୍ ମୋଡ୍",
    theme_dark: "ଡାର୍କ ମୋଡ୍",
    language: "ଭାଷା",
    compare: "ତୁଳନା କରନ୍ତୁ",
    voice_ai: "Aura AI",
    delivery_to: "ଡେଲିଭରୀ ଠିକଣା",
    hero_title: "ଭାରତର ସ୍ମାର୍ଟ ଇ-କମର୍ସ ମାର୍କେଟପ୍ଲେସ୍",
    hero_sub: "ଦ୍ରୁତ ଡେଲିଭରୀ, ପ୍ରାମାଣିକ ଉତ୍ପାଦ ଏବଂ Aura AI ଭଏସ୍ ସୁବିଧା।",
    shop_now: "ବର୍ତ୍ତମାନ କିଣନ୍ତୁ",
    explore_deals: "ଅଫର ଦେଖନ୍ତୁ",
    featured_categories: "ପ୍ରମୁଖ ବିଭାଗ",
    trending_products: "ଲୋକପ୍ରିୟ ଉତ୍ପାଦ",
    add_to_cart: "କାର୍ଟରେ ଯୋଡନ୍ତୁ",
    buy_now: "ତୁରନ୍ତ କିଣନ୍ତୁ",
    in_stock: "ଉପଲବ୍ଧ ଅଛି",
    out_of_stock: "ଷ୍ଟକ୍ ନାହିଁ",
    free_delivery: "ମାଗଣା ଡେଲିଭରୀ",
    fast_delivery: "24 ଘଣ୍ଟା ଏକ୍ସପ୍ରେସ୍ ଡେଲିଭରୀ",
    rating: "ରେଟିଂ",
    reviews: "ମତାମତ",
    discount: "ରିହାତି",
    personal_info: "ବ୍ୟକ୍ତିଗତ ବିବରଣୀ",
    current_orders: "ଚାଲୁଥିବା ଅର୍ଡର",
    past_orders: "ପୂର୍ବ ଅର୍ଡର ଇତିହାସ",
    no_active_orders: "କୌଣସି ସକ୍ରିୟ ଅର୍ଡର ନାହିଁ।",
    no_past_orders: "କୌଣସି ପୂର୍ବ ଅର୍ଡର ମିଳିଲା ନାହିଁ।",
    track_order: "ଲାଇଭ୍ ଟ୍ରାକ୍ କରନ୍ତୁ",
    invoice_download: "ଇନଭଏସ୍ ଦେଖନ୍ତୁ",
    reorder: "ପୁନର୍ବାର ଅର୍ଡର କରନ୍ତୁ",
    account_settings: "ଖାତା ଏବଂ ପସନ୍ଦ",
    theme_setting: "ଡିସପ୍ଲେ ଥିମ୍",
    language_setting: "ପସନ୍ଦିତ ଭାଷା",
    save_settings: "ସେଭ୍ କରନ୍ତୁ",
    phone_number: "ଫୋନ୍ ନମ୍ବର",
    postal_code: "ପିନ୍ କୋଡ୍",
    shipping_address: "ଡେଲିଭରୀ ଠିକଣା",
    email_address: "ଇମେଲ୍ ଠିକଣା",
    full_name: "ପୂରା ନାମ",
    city: "ସହର",
    state: "ରାଜ୍ୟ",
    checkout_title: "ସୁରକ୍ଷିତ ଚେକଆଉଟ୍",
    contact_details: "ସମ୍ପର୍କ ଏବଂ ଡେଲିଭରୀ ତଥ୍ୟ",
    enter_phone: "10 ଅଙ୍କର ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    enter_address: "ଘର ନଂ, ରାସ୍ତା ଏବଂ ଅଞ୍ଚଳ",
    enter_pincode: "6 ଅଙ୍କର ପିନ୍ କୋଡ୍ ଦିଅନ୍ତୁ",
    enter_email: "ଇମେଲ୍ ଠିକଣା ଦିଅନ୍ତୁ",
    payment_method: "ଦେୟ ପଦ୍ଧତି",
    cod: "କ୍ୟାସ୍ ଅନ୍ ଡେଲିଭରୀ",
    online_pay: "ଅନଲାଇନ୍ / UPI / କାର୍ଡ",
    place_order: "ଅର୍ଡର ନିଶ୍ଚିତ କରନ୍ତୁ",
    order_summary: "ଅର୍ଡର ସାରାଂଶ",
    total_payable: "ମୋଟ ଦେୟ ରାଶି",
    aura_greeting: "ନମସ୍କାର! ମୁଁ Aura AI, ଆପଣଙ୍କ ସ୍ମାର୍ଟ ଭଏସ୍ ଏବଂ ସପିଂ ସହାୟକ।",
    aura_listening: "Aura AI ଶୁଣୁଛି... ନିଜ ଭାଷାରେ କୁହନ୍ତୁ",
    aura_placeholder: "Aura AI କୁ ପଚାରନ୍ତୁ...",
    aura_voice_shortcuts: "ଭଏସ୍ ସର୍ଟକଟ୍",
    ask_aura: "Ask Aura"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("app_language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("app_language", language);
    document.documentElement.lang = language;
  }, [language]);

  const changeLanguage = (langCode) => {
    if (translations[langCode]) {
      setLanguage(langCode);
      try {
        const user = JSON.parse(localStorage.getItem("user") || "{}");
        if (user && user.email) {
          user.preferredLanguage = langCode;
          localStorage.setItem("user", JSON.stringify(user));
        }
      } catch (e) {
        console.warn(e);
      }
    }
  };

  const t = (key) => {
    const langDict = translations[language] || translations.en;
    return langDict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, availableLanguages: [
      { code: "en", name: "English", nativeName: "English" },
      { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
      { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
      { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
      { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
      { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" }
    ] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
